before:
  hooks:
    - go mod download
builds:
- env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
dockers:
- id: linux
  goos: linux
  goarch: amd64
  image_templates:
    - '{{ if index .Env "CI" }}ghcr.io/{{ .Env.GITHUB_REPOSITORY }}{{ else }}{{ .ProjectName }}{{ end }}:{{ .Version }}'
  build_flag_templates:
    - "--pull"
    - '--label=org.opencontainers.image.source={{ if index .Env "CI" }}{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY }}{{ else }}{{.ProjectName}}{{ end }}'
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "latest"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

