name: Build and Test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
      - name: Build
        run: go build .
      - name: Tests.
        run: go test

